client_id: "Client2"
train_configs:
  # Device
  device: "cuda"
  # Logging and outputs
  logging_output_dirname: "./output"
  logging_output_filename: "result"

# Local dataset
data_configs:
  dataset_path: "./resources/dataset/tiny_imagenet_dataset.py"
  dataset_name: "get_tiny_imagenet"
  dataset_kwargs:
    num_clients: 10
    client_id: 1
    partition_strategy: "iid"
    dataset_dir: "./datasets/RawData"
    auto_download: True
    visualization: False
    output_dirname: "./output"
    output_filename: "visualization.pdf"

comm_configs:
  grpc_configs:
    server_uri: localhost:50051
    max_message_size: 1048576
    use_ssl: False
